Title: Ekwusigo Daniel 
#Logo : 
Description: Data Analyst ,Data Scientist and a Machine Learning Engineer
Show download : False
remote_theme: pages-themes/minimal@v0.2.0
plugins: - jekyll-remote-theme
